### ISSUE TITLE
Copy / Config Issue?

### ISSUE THREAD

**Issue by iCry1337** [AltV-Projects/TypeScript-Login-Register#6]
Hello,

i have seen some issues here.

- Files from src/client will moved wrong. As example : 
![https://i.imgur.com/Z6HDt6q.png](https://i.imgur.com/Z6HDt6q.png)

- Also Client Files empty
![https://i.imgur.com/UIOCUgL.png](https://i.imgur.com/UIOCUgL.png)

**Comment by DatMayo** [comment]
I'll look into it today and report back

**Comment by DerEnderman** [comment]
Full Fix -> https://github.com/AltV-Projects/TypeScript-Login-Register/pull/8

**Comment by DatMayo** [comment]
Thx, I'll look into it tomorrow

**Comment by DatMayo** [comment]
Fixed with pr https://github.com/AltV-Projects/TypeScript-Login-Register/pull/8
